import { hasSupabaseEnv } from "@/lib/env";
import { createServerSupabaseClient } from "@/lib/supabase/server";

async function organizationContext(){if(!hasSupabaseEnv)return null;const supabase=await createServerSupabaseClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:membership}=await supabase.from("organization_memberships").select("organization_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();return membership?{supabase,organizationId:membership.organization_id}:null;}

export async function loadIntegrationState(){const context=await organizationContext();if(!context)return null;const[{data:connections},{data:issues}]=await Promise.all([context.supabase.from("sync_connections").select("provider,status,last_success_at,last_attempt_at,configuration").eq("organization_id",context.organizationId),context.supabase.from("integration_health_issues").select("provider,severity,title,detail,last_detected_at").eq("organization_id",context.organizationId).is("resolved_at",null).order("last_detected_at",{ascending:false})]);return{connections:connections??[],issues:issues??[]};}

export async function loadAdsSummary(){const context=await organizationContext();if(!context)return null;const start=new Date(Date.now()-30*86_400_000).toISOString().slice(0,10);const[{data:metrics},{data:campaigns},{data:projects}]=await Promise.all([context.supabase.from("google_ads_daily_metrics").select("entity_provider_id,impressions,clicks,cost_cents,conversions,conversion_value_cents,date").eq("organization_id",context.organizationId).eq("entity_type","campaign").gte("date",start),context.supabase.from("google_ads_campaigns").select("provider_id,name,budget_cents,status").eq("organization_id",context.organizationId),context.supabase.from("projects").select("id,booked_value_cents,collected_cents,pipeline_stage_id,lead_source").eq("organization_id",context.organizationId).ilike("lead_source","%google%")]);if(!metrics?.length)return null;const campaignMap=new Map((campaigns??[]).map(campaign=>[campaign.provider_id,campaign]));const grouped=new Map<string,{name:string;spendCents:number;clicks:number;reportedConversions:number;reportedValueCents:number}>();for(const metric of metrics){const id=metric.entity_provider_id;const current=grouped.get(id)??{name:campaignMap.get(id)?.name??id,spendCents:0,clicks:0,reportedConversions:0,reportedValueCents:0};current.spendCents+=Number(metric.cost_cents);current.clicks+=Number(metric.clicks);current.reportedConversions+=Number(metric.conversions);current.reportedValueCents+=Number(metric.conversion_value_cents);grouped.set(id,current);}return{start,end:new Date(Date.now()-86_400_000).toISOString().slice(0,10),campaigns:[...grouped.values()],spendCents:[...grouped.values()].reduce((sum,row)=>sum+row.spendCents,0),reportedConversions:[...grouped.values()].reduce((sum,row)=>sum+row.reportedConversions,0),reportedValueCents:[...grouped.values()].reduce((sum,row)=>sum+row.reportedValueCents,0),attributedLeads:(projects??[]).length,bookedRevenueCents:(projects??[]).reduce((sum,row)=>sum+Number(row.booked_value_cents),0)};}

export async function loadSearchSummary(){const context=await organizationContext();if(!context)return null;const start=new Date(Date.now()-30*86_400_000).toISOString().slice(0,10);const{data}=await context.supabase.from("search_console_daily_metrics").select("query,clicks,impressions,ctr,average_position,date").eq("organization_id",context.organizationId).gte("date",start);if(!data?.length)return null;const grouped=new Map<string,{query:string;clicks:number;impressions:number;weightedPosition:number}>();for(const row of data){if(!row.query)continue;const current=grouped.get(row.query)??{query:row.query,clicks:0,impressions:0,weightedPosition:0};current.clicks+=Number(row.clicks);current.impressions+=Number(row.impressions);current.weightedPosition+=Number(row.average_position)*Number(row.impressions);grouped.set(row.query,current);}const queries=[...grouped.values()].map(row=>({...row,ctr:row.impressions?row.clicks/row.impressions:0,position:row.impressions?row.weightedPosition/row.impressions:0})).sort((a,b)=>b.impressions-a.impressions);const totals=queries.reduce((sum,row)=>({clicks:sum.clicks+row.clicks,impressions:sum.impressions+row.impressions,weightedPosition:sum.weightedPosition+row.weightedPosition}),{clicks:0,impressions:0,weightedPosition:0});return{start,end:new Date(Date.now()-2*86_400_000).toISOString().slice(0,10),clicks:totals.clicks,impressions:totals.impressions,ctr:totals.impressions?totals.clicks/totals.impressions:0,position:totals.impressions?totals.weightedPosition/totals.impressions:0,queries:queries.slice(0,20)};}
