import { AlertTriangle, ArrowRight, CheckCircle2, FileSpreadsheet, LockKeyhole, UploadCloud } from "lucide-react";
import { importHistoricalCsv } from "./actions";

export default function ImportPage() {
  return <div className="pb-20 lg:pb-0"><div className="mb-7"><p className="font-mono text-[9px] font-bold tracking-[.15em] text-coral uppercase">Migration workspace / One-time source</p><h1 className="mt-2 font-display text-4xl tracking-[-.04em] sm:text-5xl">Bring history forward without rewriting it.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/52">Every row retains its spreadsheet ID, tab, row number, raw values, normalization result, mapping decision, and import timestamp.</p></div>
    <div className="grid gap-5 xl:grid-cols-12"><section className="paper rounded-xl border p-6 xl:col-span-8"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#e3f0df] text-moss"><FileSpreadsheet className="size-6" /></span><div><p className="text-xs font-bold">Southern Revelry historical workbook</p><p className="mt-1 break-all font-mono text-[9px] text-ink/40">1lUTpjMwMqTqh9y4N9bEHAL1lyeh0swt1i0KmaAdXuOc · Leads</p></div></div><form action={importHistoricalCsv} className="mt-6 rounded-xl border-2 border-dashed border-ink/15 bg-white/35 p-10 text-center"><input type="hidden" name="spreadsheetId" value="1lUTpjMwMqTqh9y4N9bEHAL1lyeh0swt1i0KmaAdXuOc"/><input type="hidden" name="tab" value="Leads"/><UploadCloud className="mx-auto size-8 text-ink/30" /><p className="mt-4 font-display text-2xl">Upload a Leads CSV export</p><p className="mx-auto mt-2 max-w-md text-[11px] leading-5 text-ink/45">Export only the Leads tab as CSV. Validation runs before anything is committed.</p><input required name="file" type="file" accept=".csv,text/csv" className="mx-auto mt-5 block max-w-full text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-ink file:px-4 file:py-2.5 file:text-xs file:font-bold file:text-white"/><button className="mt-4 rounded-lg bg-coral px-4 py-2.5 text-xs font-bold text-white">Validate and import</button></form><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["1. Validate","Zod checks headers and values"],["2. Review","Resolve ambiguous mappings"],["3. Commit","Idempotent database import"]].map(([title,text])=><div key={title} className="rounded-lg border bg-white/40 p-3"><p className="text-[10px] font-bold">{title}</p><p className="mt-1 text-[9px] leading-4 text-ink/42">{text}</p></div>)}</div></section>
      <aside className="space-y-5 xl:col-span-4"><section className="rounded-xl border border-marigold/45 bg-[#fff7dd] p-5"><div className="flex items-center gap-2 text-[#7a5911]"><AlertTriangle className="size-4" /><p className="font-mono text-[8px] font-bold tracking-[.12em] uppercase">Preflight expected</p></div><dl className="mt-4 space-y-3 text-xs"><div className="flex justify-between"><dt className="text-ink/50">Historical rows</dt><dd className="font-mono font-bold">≈111</dd></div><div className="flex justify-between"><dt className="text-ink/50">Likely mappings</dt><dd className="font-mono font-bold">12</dd></div><div className="flex justify-between"><dt className="text-ink/50">Silent overwrites</dt><dd className="font-mono font-bold">0</dd></div></dl></section><section className="paper rounded-xl border p-5"><div className="flex items-center gap-2"><LockKeyhole className="size-4 text-moss" /><p className="text-xs font-bold">Import guarantees</p></div><ul className="mt-4 space-y-3 text-[10px] leading-5 text-ink/52">{["Raw source values remain immutable","Unknown values enter the mapping queue","Duplicate rows use spreadsheet + tab + row","Future mappings reuse approved rules","The Sheet becomes historical after migration"].map(item=><li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-moss" />{item}</li>)}</ul><button className="mt-5 flex items-center gap-2 text-[10px] font-bold text-ink/55">View import runbook <ArrowRight className="size-3.5" /></button></section></aside></div>
  </div>;
}
