import { ArrowLeft, CalendarDays, ExternalLink, Mail, MapPin, MessageSquareText, Phone, ReceiptText, UserRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { projects } from "@/lib/mock/projects";
import { formatCents } from "@/lib/domain/money";
import { formatDate } from "@/lib/utils";

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = projects.find(item => item.id === id);
  if (!project) notFound();
  const outstanding = project.bookedCents-project.collectedCents;
  return <div className="pb-20 lg:pb-0"><Link href="/pipeline" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-ink/50"><ArrowLeft className="size-4" /> Back to pipeline</Link>
    <div className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex flex-wrap gap-2"><span className="rounded-full bg-coral px-2.5 py-1 text-[9px] font-bold text-white">{project.temperature}</span><span className="rounded-full border bg-cream px-2.5 py-1 text-[9px] font-bold">{project.stage}</span></div><h1 className="font-display text-4xl tracking-[-.04em] sm:text-5xl">{project.name}</h1><p className="mt-3 text-sm text-ink/50">{project.eventType} · {formatDate(project.eventDate)} · {project.location}</p></div><a href="https://www.honeybook.com/" target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 self-start rounded-lg bg-ink px-4 text-xs font-bold text-white">Open HoneyBook <ExternalLink className="size-4" /></a></div>
    <div className="grid gap-5 xl:grid-cols-12"><div className="space-y-5 xl:col-span-8"><section className="paper rounded-xl border p-5"><p className="font-mono text-[8px] font-bold tracking-[.14em] text-coral uppercase">Project record</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[CalendarDays,"Event",formatDate(project.eventDate)],[MapPin,"Venue",project.venue],[UserRound,"Owner",project.owner],[ReceiptText,"Source",project.source]].map(([Icon,label,value])=><div key={String(label)} className="rounded-lg border bg-white/45 p-3"><Icon className="size-4 text-ink/40" /><p className="mt-3 text-[9px] text-ink/40">{String(label)}</p><p className="mt-1 text-xs font-bold">{String(value)}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{project.services.map(service=><span key={service} className="rounded bg-turquoise/15 px-3 py-2 text-[10px] font-bold text-[#285e59]">{service} · Sheet import</span>)}</div></section>
      <section className="paper rounded-xl border"><div className="border-b px-5 py-4"><p className="font-mono text-[8px] font-bold tracking-[.14em] text-moss uppercase">Chronological record</p><h2 className="mt-1 font-display text-2xl">Activity stream</h2></div><div className="px-5">{[{title:"Proposal viewed",detail:"First view recorded; latest view 9:12 AM",source:"Another integration",icon:ReceiptText},{title:"Email sent",detail:"Package options and availability follow-up",source:"Email",icon:Mail},{title:"Proposal sent",detail:`${formatCents(project.estimatedCents)} multi-service proposal`,source:"HoneyBook webhook",icon:ReceiptText},{title:"Inquiry received",detail:`${project.source} · ${project.attribution}`,source:"Imported / attribution",icon:MessageSquareText}].map((event,index)=><div key={event.title} className="grid grid-cols-[36px_1fr] gap-3 border-b py-4 last:border-0"><span className="grid size-9 place-items-center rounded-full bg-ink text-white"><event.icon className="size-4" /></span><div><div className="flex items-center justify-between"><p className="text-xs font-bold">{event.title}</p><p className="font-mono text-[8px] text-ink/35">{index===0?"Today":`${index+1} days ago`}</p></div><p className="mt-1 text-[11px] text-ink/52">{event.detail}</p><p className="mt-2 font-mono text-[8px] text-ink/32 uppercase">Source: {event.source}</p></div></div>)}</div></section></div>
      <aside className="space-y-5 xl:col-span-4"><section className="paper rounded-xl border p-5"><p className="font-mono text-[8px] font-bold tracking-[.14em] text-ink/40 uppercase">Financial summary</p><div className="mt-4 space-y-3 text-xs">{[["Estimated",project.estimatedCents],["Booked",project.bookedCents],["Collected",project.collectedCents],["Outstanding",outstanding]].map(([label,value])=><div key={String(label)} className="flex justify-between"><span className="text-ink/48">{label}</span><span className="font-mono font-bold">{formatCents(Number(value))}</span></div>)}</div><p className="mt-4 border-t pt-3 font-mono text-[8px] text-ink/36 uppercase">Financial fields · Synced from HoneyBook</p></section><section className="rounded-xl border border-marigold/40 bg-[#fff7dd] p-5"><p className="font-mono text-[8px] font-bold tracking-[.14em] text-[#805e13] uppercase">Next follow-up · Manually maintained</p><p className="mt-3 font-display text-2xl">Today at 9:00 AM</p><p className="mt-2 text-[11px] leading-5 text-ink/55">Ask whether they want to hold the date after viewing the proposal.</p><div className="mt-4 flex gap-2"><button className="flex h-9 items-center gap-2 rounded-lg bg-ink px-3 text-[10px] font-bold text-white"><Phone className="size-3.5" /> Log call</button><button className="h-9 rounded-lg border bg-white px-3 text-[10px] font-bold">Complete</button></div></section></aside></div>
  </div>;
}
