import { CalendarDays, ChevronDown, Columns3, Filter, List, Search, SlidersHorizontal } from "lucide-react";
import Link from "next/link";
import { projects } from "@/lib/mock/projects";
import { formatCents } from "@/lib/domain/money";
import { formatDate } from "@/lib/utils";

const views = ["All leads", "Needs response", "Follow-up due", "Proposal not viewed", "Viewed, not booked", "Hot leads", "Booked & planning", "Lost"];

export default function PipelinePage() {
  return <div className="pb-20 lg:pb-0">
    <div className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="font-mono text-[9px] font-bold tracking-[.15em] text-coral uppercase">Sales pipeline / 111 historical leads</p><h1 className="mt-2 font-display text-4xl tracking-[-.04em] sm:text-5xl">Every lead, one clear next step.</h1><p className="mt-3 text-sm text-ink/52">HoneyBook-owned values are marked in the detail view. Follow-ups and temperature are maintained here.</p></div><div className="flex gap-2"><button className="flex h-10 items-center gap-2 rounded-lg border bg-cream px-3 text-xs font-bold"><Columns3 className="size-4" /> Kanban</button><button className="flex h-10 items-center gap-2 rounded-lg bg-ink px-3 text-xs font-bold text-white"><List className="size-4" /> Table</button></div></div>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{views.map((view,index) => <button key={view} className={`whitespace-nowrap rounded-full border px-3 py-2 text-[10px] font-bold ${index===0?"border-ink bg-ink text-white":"bg-cream text-ink/55"}`}>{view}{view==="Needs response"?<span className="ml-2 rounded-full bg-coral px-1.5 text-white">2</span>:null}</button>)}</div>
    <div className="paper mb-4 flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center"><label className="flex h-10 flex-1 items-center gap-2 rounded-lg border bg-white px-3"><Search className="size-4 text-ink/35" /><input aria-label="Search leads" placeholder="Search name, venue, service…" className="w-full bg-transparent text-xs outline-none" /></label><button className="flex h-10 items-center gap-2 rounded-lg border bg-white px-3 text-xs font-bold"><Filter className="size-4" /> Filters <ChevronDown className="size-3" /></button><button className="flex h-10 items-center gap-2 rounded-lg border bg-white px-3 text-xs font-bold"><CalendarDays className="size-4" /> Event date</button><button className="flex h-10 items-center gap-2 rounded-lg border bg-white px-3 text-xs font-bold"><SlidersHorizontal className="size-4" /> Columns</button></div>
    <section className="paper overflow-hidden rounded-xl border"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead className="bg-ink/[.035] font-mono text-[8px] tracking-[.11em] text-ink/44 uppercase"><tr><th className="px-5 py-3">Lead</th><th className="px-3 py-3">Stage</th><th className="px-3 py-3">Services</th><th className="px-3 py-3">Event</th><th className="px-3 py-3">Value</th><th className="px-3 py-3">Last contact</th><th className="px-3 py-3">Proposal</th><th className="px-3 py-3">Next follow-up</th><th className="px-5 py-3">Attribution</th></tr></thead><tbody className="divide-y">{projects.map(project => <tr key={project.id} className="hover:bg-marigold/[.06]"><td className="px-5 py-4"><Link href={`/leads/${project.id}`} className="font-display text-[17px] font-semibold hover:underline">{project.name}</Link><p className="mt-1 text-[9px] text-ink/40">{project.source} · {project.owner}</p></td><td className="px-3 py-4"><span className="rounded-full border bg-white px-2.5 py-1 text-[9px] font-bold">{project.stage}</span></td><td className="px-3 py-4"><div className="flex max-w-[180px] flex-wrap gap-1">{project.services.map(service=><span className="rounded bg-turquoise/15 px-2 py-1 text-[9px] font-bold text-[#285e59]" key={service}>{service}</span>)}</div></td><td className="px-3 py-4"><p className="text-xs font-bold">{formatDate(project.eventDate)}</p><p className="mt-1 text-[9px] text-ink/40">{project.venue}</p></td><td className="px-3 py-4"><p className="font-mono text-xs font-bold">{formatCents(project.estimatedCents)}</p><p className="mt-1 text-[9px] text-moss">{project.bookedCents?`${formatCents(project.collectedCents)} collected`:"Estimated"}</p></td><td className="px-3 py-4"><p className={`text-xs font-bold ${project.lastContactAt?"":"text-coral"}`}>{project.lastContactAt?formatDate(project.lastContactAt):"Never"}</p><p className="mt-1 text-[9px] text-ink/40">{project.lastContactAt?"Email · derived":"Needs response"}</p></td><td className="px-3 py-4"><span className={`text-xs font-bold ${project.proposalStatus==="Viewed"?"text-coral":project.proposalStatus==="Signed"?"text-moss":""}`}>{project.proposalStatus}</span></td><td className="px-3 py-4"><p className="text-xs font-bold">{project.nextFollowUpAt?formatDate(project.nextFollowUpAt):"—"}</p></td><td className="max-w-[170px] px-5 py-4 text-[10px] leading-4 text-ink/55">{project.attribution}</td></tr>)}</tbody></table></div></section>
  </div>;
}
