import { createHash } from "node:crypto";
import type { z } from "zod";
import { normalizeStage } from "@/lib/domain/normalization";
import { honeyBookWebhookSchema } from "./honeybook-webhook";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

type Payload=z.infer<typeof honeyBookWebhookSchema>;
const stringValue=(data:Record<string,unknown>,key:string)=>typeof data[key]==="string"?String(data[key]).trim()||null:null;
const centsValue=(data:Record<string,unknown>,key:string)=>Number.isInteger(data[key])&&Number(data[key])>=0?Number(data[key]):null;

async function sourceRecord(organizationId:string,payload:Payload){const admin=createAdminSupabaseClient();const fingerprint=createHash("sha256").update(`honeybook_zapier:${payload.event_id}`).digest("hex");const{data,error}=await admin.from("source_records").upsert({organization_id:organizationId,source_type:"honeybook_zapier",provider_record_id:payload.event_id,raw_values:{event:payload.event,event_id:payload.event_id,occurred_at:payload.occurred_at,data_keys:Object.keys(payload.data)},normalized_values:{},import_fingerprint:fingerprint},{onConflict:"organization_id,source_type,import_fingerprint"}).select("id").single();if(error)throw new Error("Unable to retain HoneyBook source record");return data.id as string;}

async function queueMapping(organizationId:string,sourceRecordId:string,fieldName:string,sourceValue:string,suggestedValue?:string|null){const admin=createAdminSupabaseClient();await admin.from("mapping_queue").upsert({organization_id:organizationId,source_record_id:sourceRecordId,field_name:fieldName,source_value:sourceValue,suggested_value:suggestedValue??null},{onConflict:"source_record_id,field_name"});}

async function findStageId(organizationId:string,sourceStage:string,sourceRecordId:string){const normalized=normalizeStage(sourceStage);if(!normalized.value){await queueMapping(organizationId,sourceRecordId,"pipeline_stage",sourceStage);return null;}const key=normalized.value.toLowerCase().replaceAll("-","_").replaceAll(" ","_");const admin=createAdminSupabaseClient();const{data}=await admin.from("pipeline_stages").select("id").eq("organization_id",organizationId).eq("key",key).maybeSingle();return data?.id??null;}

async function upsertContact(organizationId:string,payload:Payload){if(!payload.client_id)return null;const admin=createAdminSupabaseClient();const{data,error}=await admin.from("contacts").upsert({organization_id:organizationId,honeybook_client_id:payload.client_id,first_name:stringValue(payload.data,"first_name"),last_name:stringValue(payload.data,"last_name"),email_normalized:stringValue(payload.data,"email")?.toLowerCase(),phone_e164:stringValue(payload.data,"phone"),raw_provider_fields:{source:"honeybook_zapier",last_event:payload.event}},{onConflict:"organization_id,honeybook_client_id"}).select("id").single();if(error)throw new Error("Unable to store HoneyBook client");return data.id as string;}

async function upsertProject(organizationId:string,payload:Payload,contactId:string|null,sourceRecordId:string){if(!payload.project_id)return null;const admin=createAdminSupabaseClient();const sourceStage=stringValue(payload.data,"stage");const stageId=sourceStage?await findStageId(organizationId,sourceStage,sourceRecordId):null;const values:Record<string,unknown>={source_origin:"honeybook",raw_provider_fields:{source:"honeybook_zapier",last_event:payload.event}};const optionalFields=[["project_url","honeybook_url"],["project_name","name"],["event_type","event_type"],["event_at","event_at"],["venue_name","venue_name"],["city","city"],["region","region"],["lead_source","lead_source"]]as const;for(const[source,column]of optionalFields){const value=stringValue(payload.data,source);if(value)values[column]=value;}if(contactId)values.primary_contact_id=contactId;if(stageId)values.pipeline_stage_id=stageId;for(const[key,column]of[["estimated_value_cents","estimated_value_cents"],["proposal_value_cents","proposal_value_cents"],["booked_value_cents","booked_value_cents"],["collected_cents","collected_cents"]]as const){const value=centsValue(payload.data,key);if(value!==null)values[column]=value;}const{data:existing}=await admin.from("projects").select("id").eq("organization_id",organizationId).eq("honeybook_project_id",payload.project_id).maybeSingle();if(existing){const{error}=await admin.from("projects").update(values).eq("id",existing.id);if(error)throw new Error("Unable to update HoneyBook project");return existing.id as string;}const{data,error}=await admin.from("projects").insert({...values,organization_id:organizationId,honeybook_project_id:payload.project_id,name:values.name??"HoneyBook project"}).select("id").single();if(error)throw new Error("Unable to store HoneyBook project");return data.id as string;}

export async function processHoneyBookEvent(organizationId:string,payload:Payload){const admin=createAdminSupabaseClient();const sourceRecordId=await sourceRecord(organizationId,payload);const contactId=await upsertContact(organizationId,payload);let projectId:string|null=null;if(payload.project_id)projectId=await upsertProject(organizationId,payload,contactId,sourceRecordId);
  if(payload.event==="project_stage_changed"&&!stringValue(payload.data,"stage"))await queueMapping(organizationId,sourceRecordId,"pipeline_stage","[missing stage]");
  if(payload.event==="project_booked"&&!stringValue(payload.data,"stage"))await queueMapping(organizationId,sourceRecordId,"pipeline_stage","Booked trigger","Confirm the canonical stage; no stage was guessed");
  if(payload.event==="payment_received"){const paymentId=stringValue(payload.data,"payment_id");const amount=centsValue(payload.data,"amount_cents");if(projectId&&paymentId&&amount!==null)await admin.from("payments").upsert({organization_id:organizationId,project_id:projectId,provider:"honeybook_zapier",provider_id:paymentId,amount_cents:amount,paid_at:stringValue(payload.data,"paid_at")??payload.occurred_at,raw_provider_fields:{source:"honeybook_zapier"}},{onConflict:"organization_id,provider,provider_id"});else await queueMapping(organizationId,sourceRecordId,"payment","Incomplete payment payload");}
  if(projectId)await admin.from("activity_events").upsert({organization_id:organizationId,project_id:projectId,event_type:payload.event,title:payload.event.replaceAll("_"," "),source_origin:"honeybook",provider_event_id:payload.event_id,occurred_at:payload.occurred_at,metadata:{source:"honeybook_zapier"}},{onConflict:"organization_id,source_origin,provider_event_id"});
  return{projectId,contactId,sourceRecordId};}
