import { env } from "@/lib/env";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { beginSyncRun, failSyncRun, finishSyncRun } from "@/lib/integrations/sync-run";
import { GoogleAdsRestProvider } from "./google-ads";
import { SearchConsoleRestProvider } from "./search-console";
import { refreshGoogleAccessToken } from "./tokens";
import { classifyConversionOutcome, evaluateAdsHealth } from "./health";

function reportingRange(days=30){const end=new Date(Date.now()-86_400_000);const start=new Date(end.getTime()-(days-1)*86_400_000);return{startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)}}

export async function syncGoogleAds(organizationId:string){
  const runId=await beginSyncRun(organizationId,"google_ads","daily_reporting");if(!runId)return{overlap:true};const admin=createAdminSupabaseClient();
  try{const{data:connection}=await admin.from("sync_connections").select("id,encrypted_refresh_token,configuration").eq("organization_id",organizationId).eq("provider","google_ads").eq("status","connected").single();if(!connection?.encrypted_refresh_token||!env.GOOGLE_ADS_DEVELOPER_TOKEN||!env.GOOGLE_ADS_API_VERSION)throw new Error("Google Ads connection is incomplete");
    const configuration=(connection.configuration??{})as Record<string,unknown>;const customerId=String(configuration.customerId??env.GOOGLE_ADS_CUSTOMER_ID??"");if(!customerId)throw new Error("Google Ads customer ID is missing");
    const provider=new GoogleAdsRestProvider({accessToken:await refreshGoogleAccessToken(String(connection.encrypted_refresh_token)),developerToken:env.GOOGLE_ADS_DEVELOPER_TOKEN,customerId,managerCustomerId:String(configuration.managerCustomerId??env.GOOGLE_ADS_MANAGER_CUSTOMER_ID??"")||undefined,apiVersion:env.GOOGLE_ADS_API_VERSION});
    const[rows,actions,conversionRows]=await Promise.all([provider.getCampaignDaily(reportingRange()),provider.getConversionActions(),provider.getConversionActionDaily(reportingRange())]);
    const{data:account,error:accountError}=await admin.from("google_ads_accounts").upsert({organization_id:organizationId,customer_id:customerId,manager_customer_id:String(configuration.managerCustomerId??"")||null,display_name:"Southern Revelry Google Ads"},{onConflict:"organization_id,customer_id"}).select("id").single();if(accountError)throw new Error("Unable to store Google Ads account");
    const campaigns=[...new Map(rows.map(row=>[row.campaignId,row])).values()];for(const campaign of campaigns)await admin.from("google_ads_campaigns").upsert({organization_id:organizationId,account_id:account.id,provider_id:campaign.campaignId,name:campaign.campaignName,status:campaign.campaignStatus,budget_cents:campaign.budgetCents},{onConflict:"account_id,provider_id"});
    if(rows.length)await admin.from("google_ads_daily_metrics").upsert(rows.map(row=>({organization_id:organizationId,account_id:account.id,date:row.date,entity_type:"campaign",entity_provider_id:row.campaignId,impressions:row.impressions,clicks:row.clicks,cost_cents:row.costCents,conversions:row.conversions,conversion_value_cents:row.conversionValueCents,impression_share:row.impressionShare})),{onConflict:"account_id,date,entity_type,entity_provider_id,device,geographic_area,conversion_action"});
    if(actions.length)await admin.from("google_ads_conversion_actions").upsert(actions.map(action=>{const last=conversionRows.filter(row=>row.actionId===action.providerId&&row.conversions>0).sort((a,b)=>b.date.localeCompare(a.date))[0];return{organization_id:organizationId,account_id:account.id,provider_id:action.providerId,name:action.name,category:action.category,business_outcome:classifyConversionOutcome(action.name),status:action.status,primary_for_goal:action.primaryForGoal,enhanced_conversions_enabled:action.enhancedConversionsEnabled,last_conversion_at:last?`${last.date}T00:00:00Z`:null}}),{onConflict:"account_id,provider_id"});
    if(conversionRows.length)await admin.from("google_ads_daily_metrics").upsert(conversionRows.map(row=>({organization_id:organizationId,account_id:account.id,date:row.date,entity_type:"conversion_action",entity_provider_id:row.actionId,conversion_action:row.actionName,conversions:row.conversions,conversion_value_cents:row.conversionValueCents})),{onConflict:"account_id,date,entity_type,entity_provider_id,device,geographic_area,conversion_action"});
    const issues=evaluateAdsHealth(actions,rows,conversionRows);const{data:googleProjects}=await admin.from("projects").select("id,booked_value_cents,lead_attribution(gclid,gbraid,wbraid)").eq("organization_id",organizationId).ilike("lead_source","%google%");for(const project of googleProjects??[]){const touches=(project.lead_attribution??[])as Array<{gclid?:string|null;gbraid?:string|null;wbraid?:string|null}>;if(!touches.some(touch=>touch.gclid||touch.gbraid||touch.wbraid)){issues.push({key:"lead_missing_click_identifier",severity:"warning",title:"Lead missing click identifier",detail:"A Google-sourced lead has no gclid, gbraid, or wbraid and cannot be matched deterministically.",entityProviderId:project.id});if(Number(project.booked_value_cents)>0)issues.push({key:"booking_unmatched",severity:"critical",title:"Booking cannot be matched to a campaign",detail:"A booked Google-sourced project has no stable click identifier.",entityProviderId:project.id});}}await admin.from("integration_health_issues").update({resolved_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("provider","google_ads").is("resolved_at",null);if(issues.length)await admin.from("integration_health_issues").upsert(issues.map(issue=>({organization_id:organizationId,connection_id:connection.id,provider:"google_ads",issue_key:issue.key,severity:issue.severity,title:issue.title,detail:issue.detail,entity_provider_id:issue.entityProviderId??"account",last_detected_at:new Date().toISOString(),resolved_at:null})),{onConflict:"organization_id,provider,issue_key,entity_provider_id"});
    const now=new Date().toISOString();await admin.from("sync_connections").update({last_attempt_at:now,last_success_at:now,status:issues.some(issue=>issue.severity==="critical")?"degraded":"connected"}).eq("id",connection.id);await finishSyncRun(runId,{processed:rows.length+actions.length+conversionRows.length});return{rows:rows.length,actions:actions.length,conversionRows:conversionRows.length,issues:issues.length};
  }catch(error){await failSyncRun(runId,"google_ads",error);await admin.from("sync_connections").update({status:"failed",last_attempt_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("provider","google_ads");throw error;}}

export async function syncSearchConsole(organizationId:string){
  const runId=await beginSyncRun(organizationId,"search_console","daily_reporting");if(!runId)return{overlap:true};const admin=createAdminSupabaseClient();
  try{const{data:connection}=await admin.from("sync_connections").select("id,encrypted_refresh_token,configuration").eq("organization_id",organizationId).eq("provider","search_console").eq("status","connected").single();if(!connection?.encrypted_refresh_token)throw new Error("Search Console connection is incomplete");const configuration=(connection.configuration??{})as Record<string,unknown>;const propertyUri=String(configuration.propertyUri??env.GOOGLE_SEARCH_CONSOLE_PROPERTY??"");if(!propertyUri)throw new Error("Search Console property is missing");const provider=new SearchConsoleRestProvider({accessToken:await refreshGoogleAccessToken(String(connection.encrypted_refresh_token)),propertyUri});const[rows,sitemaps]=await Promise.all([provider.getDaily(reportingRange(16)),provider.getSitemaps()]);const{data:property,error}=await admin.from("search_console_properties").upsert({organization_id:organizationId,property_uri:propertyUri,display_name:"Southern Revelry",permission_level:"siteOwner",last_success_at:new Date().toISOString()},{onConflict:"organization_id,property_uri"}).select("id").single();if(error)throw new Error("Unable to store Search Console property");if(rows.length)await admin.from("search_console_daily_metrics").upsert(rows.map(row=>({organization_id:organizationId,property_id:property.id,date:row.date,query:row.query,page:row.page,country:row.country,device:row.device,search_appearance:row.searchAppearance,clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.averagePosition})),{onConflict:"property_id,date,query,page,country,device,search_appearance"});if(sitemaps.length)await admin.from("search_console_sitemaps").upsert(sitemaps.map(item=>({organization_id:organizationId,property_id:property.id,path:item.path,submitted_at:item.submittedAt,last_downloaded_at:item.lastDownloadedAt,warnings:item.warnings,errors:item.errors,status:item.errors?"error":item.warnings?"warning":"healthy"})),{onConflict:"property_id,path"});const now=new Date().toISOString();await admin.from("sync_connections").update({last_attempt_at:now,last_success_at:now,status:"connected"}).eq("id",connection.id);await finishSyncRun(runId,{processed:rows.length+sitemaps.length});return{rows:rows.length,sitemaps:sitemaps.length};
  }catch(error){await failSyncRun(runId,"search_console",error);await admin.from("sync_connections").update({status:"failed",last_attempt_at:new Date().toISOString()}).eq("organization_id",organizationId).eq("provider","search_console");throw error;}}
